### ISSUE TITLE
Multiple destination backups  - None done if first one fails

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-gpl#104] opened 2019-09-20 07:22 UTC
I have set up multiple servers with two backup destinations.
![Backupsettings](https://user-images.githubusercontent.com/45786226/65305474-8def9c00-db83-11e9-9632-ae2c913aa9d4.png)

The first one via SSH to an offsite server (primary/most important one, in case the whole server crashes), the second one as local file (in case of user error, to be able to quickly recover a deleted file for example).

I recently (once last week, and once yesterday) restarted the server (that is the target for den SSH backups) shortly before the backups were started, and it was not completely online when the backups began.

All the servers that tried to push their backups via SSH failed to do their backups completly.
I understand that due to the timeout of the sssh the offsite backup could not be done, but at least the second local one should have been done. 

> Backup failed! See the progress output above for the reason why. Total backup time was 00 minutes, 16 seconds.
>
>Virtual servers that failed :
>    ***
>    
>...
>
>    ***
>Sent by Virtualmin at: ***
>
>Failed to connect to SSH server : ssh: connect to host *** port ***: No route to host
lost connection
>
>Deleting backups from /*** on SSH *** older than 21 days ..
    .. failed to list directory via SSH : ssh: connect to host *** port ***: No route to host
>
>
>    Deleting backups from local file /*** older than 14 days ..
>        Deleting directory /***, which is 14 days old ..
>        .. deleted 469.52 MB.
>
>    .. deleted 1 old backups, and skipped 13 that were not old enough

The local directory was created but it was emtpy.

It is my fault for selecting the `Continue with other features and servers` instead of `Continue, but don't purge old backups` which made the backup remove the old local backups even if **had** detected an error.

Switching the order of the backups is no option, as the "local" backup-destination is a NFS-mounted disk, which could be unmounted while the backup is running resulting in the same problem …

**Comment by jcameron** [comment] 2019-09-22 00:08
So just to confirm, did you have "Continue with other features and servers" selected? If so, other destinations should still have been written to ..

**Comment by PitWenkin** [comment] 2019-09-22 12:35
Yes, I just rechecked. All 3 servers that failed, have (and had at that time as I did not change anything) `Continue with other features and servers` selected.

The local directory in which the second destination should be saved is defined as `/***/***/***/%Y-%m-%d-i`and a folder with a name 2019-09-19-i has been created in the right folder on all 3 servers but it is empty. The second backup was therefore started, but somehow not completed.

I should be able to reproduce the timeout on the ssh backup on a test-server, and show you the output of any logfile if you want …

**Comment by jcameron** [comment] 2019-09-22 21:22
Do you have the backup setup to copy files to the final destination one by one, or only after all domains are backed up?

**Comment by PitWenkin** [comment] 2019-09-23 06:02
Both `Transfer each virtual server after it is backed up` and `One file per server` are checked if that answers your question

I just saw there is a point `Action if destination is in use` under `Schedule and reporting` which is set to `Cancel this backup`  which could be the reason for my problem? But the other option `Kill the running backup`does not sound good either …

![Schedule_and_reporting](https://user-images.githubusercontent.com/45786226/65404181-cc7d9480-ddd7-11e9-8b6d-b64d7594bafa.png)

For the rest of the config; Each server is backuped, with all features except logfiles and logrotation conf:

![Features_and_settings](https://user-images.githubusercontent.com/45786226/65404358-6e04e600-ddd8-11e9-9495-760c084f37c0.png)

**Comment by PitWenkin** [comment] 2019-09-29 18:07
I have reproduced the whole thing on a test server, where a simply blocked the ssh calls on the destination machine.
The local backup folder is created but has no content. It does not matter if I select `Continue with other features and servers` or `Continue, but don't purge old backups`.  None creates a local backup. The second option however does no try to delete old backups (At least that works).

I tried changing the output of the backup command to a `/tmp` file, but nothing was returned
https://github.com/virtualmin/virtualmin-gpl/blob/4185857bf911fce1217361866f51effe1d6ba459/backup.cgi#L25

I tried to understand the whole process in
https://github.com/virtualmin/virtualmin-gpl/blob/d5a8ac6f84dd7c71aab902316fb831387559f9b0/backups-lib.pl#L297

but did not get far, except that I think this https://github.com/virtualmin/virtualmin-gpl/blob/d5a8ac6f84dd7c71aab902316fb831387559f9b0/backups-lib.pl#L309
is the reason why the local folder is always there even if emtpy

**Comment by jcameron** [comment] 2019-09-29 20:21
Can you post the whole output from the backup process (done in the UI) here? I'm interested to see where it fails ... also, it's odd that the `ssh` backup is done first, as Virtualmin should re-order the destinations automatically to do the local file first.

**Comment by PitWenkin** [comment] 2019-09-30 06:53
```
Starting backup of 1 domains to /Backups/*** on SSH server ***, local file /Backups/*** ..
Failed to connect to SSH server : ssh: connect to host *** port 10022: Connection refused lost connection 

Backup failed! See the progress output above for the reason why.
```

Could it be the non-standard port?
Even though I've entered a username and a password for the ssh connection, it actually uses ssh-keys.

I have never used the backup in UI (`Backup Now`) to debug this until now. Only `Backup In Background`or the automatic/scheduled one. But the symptoms are all the same: Creates local folder (at the beginning of the backup process according to the timestamp) but does not store backup in it.

**Comment by jcameron** [comment] 2019-10-01 06:37
Ok, I see the cause of this bug now - it will be fixed in the next Virtualmin release.

**Closed by jcameron** 2019-10-01 06:37 UTC
