### ISSUE TITLE
Virtualmin / Webmin - Webmin servers index, fastrpc doesn't work on ipv6 (to enable BIND cluster)

### ISSUE THREAD

**Issue by abclution** [virtualmin/virtualmin-gpl#332] opened 2021-11-25 07:40 UTC
I know this is more of a Webmin thing but due to Virtualmin DNS clustering being a pretty typical usage it might belong here.

Trying to use a ipv6 connection when adding a server to "Webmin Servers Index" and enabling Make fast RPC calls, always gives an error.

Failed to connect to fastrpc.cgi : Failed to IPv6 connect to xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:10001 : Connection refused

Of course googling it points to a firewall issue but in this case it is not. 

Tested it on a completely open (all ports open) global (public) ipv6 network as well as a point to point ipv6 vpn. In all cases the message is the same.

No entries in the log other than seeing the connection

fccc:bbb:de42:631e:e611::1 - root [25/Nov/2021:09:34:49 +0200] "POST /fastrpc.cgi HTTP/1.0" 200 47

It seems perhaps the webmin fastcgi listening process doesn't actually start properly on the ipv6 address on the remote end. 

Using ipv4 for endpoints works fine (as long as firewall ports are open/availiable. (10001-10xxx, depending on how many servers are clustered))

Also ipv6 works without fastrpc enabled.

I remember coming across this issue a few years ago and forgot to report it.

**Comment by jcameron** [comment] 2021-11-25 18:55
Thanks for reporting this!  

On the master system, when you add an entry to Webmin Servers Index, are you adding it with an IPv6 address or a hostname? If a hostname, does that resolve to IPv4 and/or IPv6 addresses?

**Comment by abclution** [comment] 2021-11-27 18:26
Hey @jcameron 

Well, several ways I have tried. But with DNS and with IP 4/6.
ex With DNS

Have a dns name  
ns2.dns.blah.com which has A and AAAA records  - FastRPC works but it ends up using the ipv4 address
ns2.dns6.blah.com which is just the AAAA record - FastRPC wont work, regular does.
ns2.dns4.blah.com A record only and so on. - FastRPC works.

I also tried with the IP6 address specifically and it also seemed to do exactly the same thing.
The only thing which I haven't checked, is that my systems have multiple IPv6 addresses and I haven't tried to disabled and only try with a single ipv6 address active. 

I noticed some weirdness with a few different services kinda randomly choosing which ipv6 address to use for their external communication and I have a suspicion maybe the RPC interface is being initiated on the wrong IPv6 address. Will also check that and let you know

**Comment by jcameron** [comment] 2021-11-27 19:59
Ok, the issue is that the current Webmin code doesn't support fastRPC connections over IPv6 only - but it will try IPv4 where possible. We really should fix this, but as a work-around you can just use a hostname that also resolves to a v4 address.

**Comment by abclution** [comment] 2021-11-27 20:15
Yeah, I've worked around it.. but banged my head for quite a while trying to figure out what I was doing wrong.

There is another Virtualmin specific IPv6 issue regarding server templates as well.

Server Template -> Bind DNS -> Additionally Configured nameservers
Adding a server by dns name that only has a AAAA record fails when saving the template
ex  ns.dns6.blah.com 
"Failed to save server template. Additional nameserver ns.dns6.blah.com doesn't exist"



I should probably create another issue for this as well.

**Comment by jcameron** [comment] 2021-11-27 20:27
Thanks, that one is easy to fix.

**Comment by jcameron** [comment] 2021-11-28 03:23
Ok, I have checked in another fix that will allow RPCs to work with IPv6-only hosts : https://github.com/webmin/webmin/commit/f8be02018cc21978eca8abf40848ccd903df4cf0

**Closed by jcameron** 2021-11-28 03:23 UTC
