### ISSUE TITLE
Cloudflare DNS: Request wildcard Let's Encrypt certificate upon domain creation time

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#607] opened 2023-08-10 19:19 UTC
If a new top-level server is created using **Create Virtual Server** page and **Virtualmin Configuration / SSL settings** page has **Request wildcard Let's Encrypt certificate** set to **Yes**, wildcard certificate still is _not_ being requested.

However, doing it later manually using **Server Configuration ⇾ SSL Certificate** page works just fine.

**Comment by jcameron** [comment] 2023-08-11 04:27
Does this virtual server have the DNS feature enabled?

**Comment by jcameron** [comment] 2023-08-11 04:32
Ok I see the cause of this bug ... it'll be fixed in the next release!

**Closed by jcameron** 2023-08-11 04:32 UTC

**Comment by iliajie** [comment] 2023-08-11 09:30
Great, thanks! That patch fixes the problem.
