### ISSUE TITLE
Orphan DNS record after enabling/disabling DNSSEC

### ISSUE THREAD

**Issue by ADDISON74** [virtualmin/virtualmin-gpl#604] opened 2023-08-05 22:09 UTC
Go to **```Virtualmin > Server Configuration > DNS Option```** and choose **Yes** for **DNSSEC signature enabled**. Click the [Save] button.

Go to **```Virtualmin > Server Configuration > DNS Option```** and click the [Manually Edit Records] button.  After the last row related to SPF a lot of rows were added. 

Go to **```Virtualmin > Server Configuration > DNS Option```** and choose **No** for **DNSSEC signature enabled**. Click the [Save] button.

Go to **```Virtualmin > Server Configuration > DNS Option```** and click the [Manually Edit Records] button.  The row related to SPF should be the last one but there is another one after it

```domain.tld.	0	IN	NSEC3PARAM	1 0 0 -```

This one is an orphan left behind by DNSSEC.

**Comment by jcameron** [comment] 2023-08-06 04:31
Can you attach a screenshot of the extra records?

**Comment by ADDISON74** [comment] 2023-08-06 07:10
The line is mentioned n my post,

**Comment by jcameron** [comment] 2023-08-06 16:51
Ok I see the cause of this now - it will be fixed in the 2.102 Webmin release.

**Closed by jcameron** 2023-08-06 16:51 UTC
