### ISSUE TITLE
Virtualmin shouldn't show home dir disk space warnings to all users

### ISSUE THREAD

**Issue by danboid** [virtualmin/virtualmin-gpl#368] opened 2022-02-07 11:03 UTC
We are running Virtualmin Pro under Ubuntu 18.04 using ZFS for the users home directories. Each vmin user has a dedicated ZFS dataset for their home directory. When a vmin user uses all of the inodes available in their home dir/dataset as allowed by their current quota, virtualmin displays a disk space warning on the system information screen for all users, causing unnecessary panic. These disk space warnings should only be displayed to the affected user and the master admin instead of being shown to every user on the server.

**Comment by jcameron** [comment] 2022-02-07 22:28
Actually I think these should only be shown to the master admin, since end users shouldn't need to worry about disk space.

What's the exact error message that you're seeing?

**Comment by danboid** [comment] 2022-02-07 23:08
![vmin-no-free-inodes](https://user-images.githubusercontent.com/1429783/152887437-cd0c148e-96c0-43f6-a892-4b84a26e157a.png)

**Comment by jcameron** [comment] 2022-02-08 01:40
Ok, I see the cause of this bug ... it will be fixed in the next Virtualmin release.

**Closed by jcameron** 2022-02-08 01:40 UTC

**Comment by danboid** [comment] 2022-02-08 10:08
Thanks for the quick fix Jamie!
