### ISSUE TITLE
SSL service certificates won't go away with disabled web

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#398] opened 2022-05-24 23:22 UTC
Jamie, service certificates for Dovecot (and all other services too) are **not removed**, if feature Apache SSL website is disabled, either in Features and Plugins page or for a specific domain (for example manually setting `ssl=0` on domain config)!

The same is true for Nginx SSL features.

I don't think we should tie these two separate functionalities together, as, in case, SSL certificates are stored under user home (old way), when home and SSL certificates are deleted, all related services (Postfix, Dovecot, Webmin and Usermin) won't be able to restart/start.

If we delete actual domain we must always delete service certificates from other services _disregard_ of enabled features.

Also, I remember last year you announced a long waited feature which was decoupling use of Apache SSL from SSL used in another services. Well, running the latest version of Virtualmin 7.1, and disabling Apache SSL (properly using Virtualmin), also clears service certificates from other services, while shouldn't, right?

**Comment by neosonic2** [comment] 2022-05-25 03:20
I second this issue - it's a pain to have to go into something like /etc/dovecot/dovecot.conf and manually remove SSL service certificate definitions for a domain name that was deleted in Virtualmin because Virtualmin failed to remove these automatically. And if I don't catch it right away, then our IMAP service becomes unavailable for clients. To be honest I think there may have been a time when this worked properly but I can't remember for the life of me when that would have bee; for as long as I can remember, I've had to manually delete SSL entries in Dovecot when a domain is deleted.

Note this doesn't seem to happen with Postfix; Virtualmin seems to be able to remove SSL certificate entries from the TLS server SNI map file without a problem (tls_server_sni_maps = hash:/etc/postfix/vmail_ssl.map).

**Comment by jcameron** [comment] 2022-05-25 05:17
This does look like a bug if the Dovecot SSL config for a domain isn't cleaned up when the domain is deleted.

Does this happen if you simply create a virtual server with SSL enabled, and then remove it? If so, can someone post the block that gets left in `dovecot.conf` ?

**Comment by neosonic2** [comment] 2022-05-25 05:22
So far this happens when I delete a virtual server that had mail/spa/virus enabled as well as Nginx and Nginx SSL. I don’t have a test environment to be able to just create and delete a virtual server without this issue causing our main Dovecot IMAP server to fail, but I can post one of our existing SSL blocks that I would have to delete if that domain were deleted and this issue cropped up:

local_name martinsamishfurniture.com {
  ssl_cert = </home/martins/ssl.combined
  ssl_key = </home/martins/ssl.key
}
local_name *.martinsamishfurniture.com {
  ssl_cert = </home/martins/ssl.combined
  ssl_key = </home/martins/ssl.key
}

**Comment by jcameron** [comment] 2022-05-25 05:44
Is this issue specific to Nginx, or does it also happen for anyone when using Apache?

**Comment by iliajie** [comment] 2022-05-25 14:04
> Does this happen if you simply create a virtual server with SSL enabled, and then remove it?

No, this bug doesn't happen if you just add a domain and then remove it.

> If so, can someone post the block that gets left in dovecot.conf

The block is standard, i.e.:

```
local_name ubuntu20-gpl-5.local {
  ssl_cert = </etc/ssl/virtualmin/165341998444713/ssl.combined
  ssl_key = </etc/ssl/virtualmin/165341998444713/ssl.key
}
local_name *.ubuntu20-gpl-5.local {
  ssl_cert = </etc/ssl/virtualmin/165341998444713/ssl.combined
  ssl_key = </etc/ssl/virtualmin/165341998444713/ssl.key
}
```

How to reproduce the problem:

  1. Disassociate SSL website from a domain
  2. Delete the domain

Result:

All service certificates records will be left (not only Dovecot).

**Comment by neosonic2** [comment] 2022-05-25 14:08
In my findings, this issue also occurs if you delete a domain without disassociating its SSL website first.

**Comment by jcameron** [comment] 2022-05-25 22:36
Ah, I see ... so by "Disassociate SSL website from a domain" do you mean turning off the SSL feature.

**Comment by iliajie** [comment] 2022-05-25 22:52
Yes, exactly.

**Comment by jcameron** [comment] 2022-05-26 02:43
Which version of the `virtualmin-nginx-ssl` plugin are you running there? 

The cleanup of per-service SSL certs should be done by this code : https://github.com/virtualmin/virtualmin-nginx-ssl/commit/b0f0031725d5de4352e50282cfa16b28d9e5cc14

**Comment by jcameron** [comment] 2022-05-26 06:01
Also I just tried to reproduce this on a fully updated system using Nginx as the webserver, with the commands : 

```
virtualmin create-domain --domain sslcopy.com --dir --unix --virtualmin-nginx --virtualmin-nginx-ssl --pass smeg
virtualmin disable-feature --domain sslcopy.com --virtualmin-nginx-ssl
virtualmin delete-domain --domain sslcopy.com
```

But I confirmed that the Dovecot config was cleaned up successfully after the second command.

**Comment by iliajie** [comment] 2022-05-26 08:24
With the steps you've taken, it just works with Nginx, and works just fine with Apache too, because service certificate is cleared on the stage of disabling SSL feature.

Although, do we really want to clear SSL in all other services when SSL for a website was disabled? I remember it was advertised as a feature, to separate disabling SSL website feature and keeping SSL in other services?

By the way, why don't we explicitly say which SSL services gets enabled/disabled?

On create and edit pages there could be a new Enable SSL checkbox with intermediate states (on, off, partially). By default, all SSL features would be set to on. On the side of the label of that checkbox there could be an arrow to open an accordion/drop-down, where you could clearly pick which SSL services are enabled/disabled

For example:

DNS enabled
SSL enabled >
   Apache (or Nginx)
   Postfix
   Dovecot
   Webmin
   Usermin
Apache website
...

**Comment by jcameron** [comment] 2022-05-27 06:16
@iliajie you're right that we should keep the SSL service certs until the domain is entirely removed, since they are now decoupled from the SSL website.

**Comment by jcameron** [comment] 2022-05-27 06:25
@neosonic2 I did a test where I created and then immediately deleted a domain, and confirmed that the Dovecot config was cleaned up OK.

**Comment by iliajie** [comment] 2022-05-27 06:25
Great, so removing service certificates on disabling Apache SSL feature is a bug.

Also, let's separate SSL certificates control into suggested scheme:

```
DNS enabled
SSL enabled >
   Apache (or Nginx)
   Postfix
   Dovecot
   Webmin
   Usermin
Apache website enabled 
MariaDB databases enabled 
...
```

I can fairly easily make it work UI wise. Perhaps, fix server side too but that won't be that easily (quickly) for me.

How about I do UI change, make a PR and then you do the server side fixes to separate control over each service certificate?

**Comment by neosonic2** [comment] 2022-05-27 12:28
@jcameron That’s interesting. So perhaps there is a specific bug/issue on my system causing this to occur? Where would I begin to look for something like that?

**Comment by jcameron** [comment] 2022-05-28 05:07
@neosonic2 is there anything special about your installation, such as changes from the default configuration?

**Comment by neosonic2** [comment] 2022-05-28 05:23
@jcameron Yes but I’m not sure what would be relevant to this discussion.

For example, we have custom post-action shell scripts that Virtualmin executes whenever a virtual server is created, modified, or deleted (using the “Command to run after making changes to a server” option), but these mainly do things like pull in c changes to Websites from our Git repositories, ensure SSL certificates and other files are synced across servers in our Web cluster, and ensure users and groups are in sync across the cluster as well. These don’t touch Dovecot or Postfix configurations except to copy over relevant files between members of the cluster.

As far as Dovecot-specific changes, I’ve enabled additional protocols like LMTP and Sieve, and have changed a few other settings contained within files inside /etc/dovecot/conf.d, but nothing too dramatic. Most of our Virtualmin installation is pretty standard, with like I said those post-action scripts performing some extra tasks that either can’t be easily set up through the Virtualmin UI or require customizations not currently available in Virtualmin.

Standard things though like home directory paths, SSL paths and filenames (/home/{user}/ssl.cert, etc.), and other standard Virtualmin things are mostly kept at their defaults.

If you’ve got something specific in mind regarding changes from the default configuration let me know and I’ll try to provide a better answer.

**Comment by jcameron** [comment] 2022-05-28 06:05
One more thing to check is whether Virtualmin is recognizing the per-service certs correctly.

After creating a domain with SSL, if you SSH in and run `virtualmin list-service-certs --domain example.com --multiline` , what does it output?

**Comment by neosonic2** [comment] 2022-05-28 17:47
***@***.***:~# virtualmin list-service-certs --domain ralphandrosiesny.com --multiline
Invalid Nginx config line 	set_real_ip_from 192.168.255.0/24 ;
 at 62
dovecot:
    Service type: domain
    Cert file: /home/ralph/ssl.combined
    CA file: /home/ralph/ssl.combined
    Domain name: ralphandrosiesny.com
    Service port: 993
postfix:
    Service type: domain
    Cert file: /home/ralph/ssl.cert
    CA file: /home/ralph/ssl.ca
    Domain name: ralphandrosiesny.com
    Service port: 587

**Comment by jcameron** [comment] 2022-05-28 18:30
Ok that looks fine, other than that warning about an "Invalid Nginx config line" which is harmless.

Does this domain have a valid cert from Let's Encrypt?

**Comment by neosonic2** [comment] 2022-05-28 18:33
Yeah, now that you mention it I was actually wondering about that warning. The line in question comes from the main /etc/nginx/nginx.conf file, which I’ve heavily customized to add features like support for picking up the client’s real IP address as forwarded by our load balancer since users don’t connect directly to our Web servers. I don’t know why Virtualmin would complain the line is invalid when to Nginx that’s a valid config parameter.

Anyways, yes, the domain has a Let’s Encrypt wildcard certificate. It’s associated entries in /etc/dovecot/dovecot.conf look like this:

local_name ralphandrosiesny.com {
  ssl_cert = </home/ralph/ssl.combined
  ssl_key = </home/ralph/ssl.key
}
local_name *.ralphandrosiesny.com {
  ssl_cert = </home/ralph/ssl.combined
  ssl_key = </home/ralph/ssl.key
}

**Comment by jcameron** [comment] 2022-05-28 20:31
Can you post that entire line to this bug report? I'd like to double-check that it's not confusing Virtualmin's config parser.

**Comment by neosonic2** [comment] 2022-05-28 20:53
I think this is the nginx.conf line Virtualmin was complaining about:

set_real_ip_from 192.168.255.0/24 ;

The Linode load balancer we use has a private IP address in that network range that, according to Linode, can change frequently, so I had to configure Nginx to trust the IP address information coming from any IP on that particular range as any of them could be the load balancer (but none of them will be the Linodes of other customers).

**Comment by iliajie** [comment] 2022-05-28 21:13
> Anyways, yes, the domain has a Let’s Encrypt wildcard certificate. It’s associated entries in /etc/dovecot/dovecot.conf look like this:

Jamie, we really should find a better place to where to put our records, rather than in `/etc/dovecot/dovecot.conf` file.

**Comment by jcameron** [comment] 2022-05-28 21:14
@iliajie maybe, but that's a separate issue. Let's keep this bug on-topic..

**Comment by jcameron** [comment] 2022-05-28 21:15
@neosonic2 I think the issue here is the space before the semicolon at the end of the line. I will fix Virtualmin to not care about that..

**Comment by neosonic2** [comment] 2022-05-28 22:19
@jcameron Oh wow, thank you for pointing that out. I didn’t even realize there was a space before the semicolon. The screen reading program I use (as a visually impaired individual) didn’t report it until I read the line by character after you mentioned it. I’ve corrected it in the config and now, Virtualmin no longer complains about it when I rerun that command.

I’m guessing though that the output from the command doesn’t indicate why Virtualmin isn’t deleting SSL lines from dovecot.conf?

**Comment by jcameron** [comment] 2022-05-29 00:53
Yeah, fixing that semicolon issue isn't going to resolve the underlying problem.

Can you check for me which version of the "Virtualmin Nginx SSL" plugin you have installed there? It will show up on the Features and Plugins page.

**Comment by chris001** [comment] 2022-05-29 00:57
FYI @iliajie @jcameron Very good feature request:
#324  **Feature Request: Move SSL certs from `dovecot.conf` to `local.conf`**

**Comment by neosonic2** [comment] 2022-05-29 00:58
@jcameron Version 2.23.

**Comment by jcameron** [comment] 2022-05-29 01:05
@neosonic2 2.23 would be the version for the "Nginx website" plugin, but how about "Nginx SSL website" ?

**Comment by neosonic2** [comment] 2022-05-29 01:06
@jcameron Oh sorry, my bad, version 1.17.

**Comment by jcameron** [comment] 2022-05-29 01:19
Ok, that is indeed the latest version.

One more thing to try - after creating the domain, try removing just the Dovecot cert with `virtualmin install-service-cert --domain ralphandrosiesny.com --service dovecot --remove-domain`

**Comment by neosonic2** [comment] 2022-05-29 01:20
@jcameron How can I re-add the service certificate afterwards/if there is a problem, by just removing the —remove-domain argument?

**Comment by jcameron** [comment] 2022-05-29 01:26
You can put it back by running `virtualmin install-service-cert --domain ralphandrosiesny.com --service dovecot --add-domain`

**Comment by neosonic2** [comment] 2022-05-29 01:31
@jcameron The process completes successfully with the following output from Virtualmin:

Removing from service dovecot for ralphandrosiesny.com ..
.. done

When I check /etc/dovecot/dovecot.conf, the entire entry for the domain (including the wildcard domain) is gone. Adding it back with the second command you gave me results in the entries being added back to the bottom of the configuration file properly and the following output being printed:

Copying to service dovecot for ralphandrosiesny.com ..
.. done

**Comment by jcameron** [comment] 2022-05-29 05:46
Hmmm .. I am having trouble re-producing this issue, or triggering it outside of deletion of a domain.

The only way I could debug it further is with access to a system that's experiencing the issue.

**Comment by PitWenkin** [comment] 2022-05-31 05:35
Hi guys just reminding you that 3 years ago I already reported this in #91.

Somehow it was fixed then, and I never had this problem again (didn't delete many virtual servers since then)

> In my findings, this issue also occurs if you delete a domain without disassociating its SSL website first.

**Comment by jcameron** [comment] 2022-05-31 06:00
@PitWenkin unfortunately there have been a few different causes of this bug over the years, so even if we fixed the issue you originally reported, it may have cropped up again in a new form.

**Comment by neosonic2** [comment] 2022-05-31 21:00
@jcameron I can use the Virtualmin Support module to give you access to our production system running Virtualmin that is experiencing this issue, or just set up a regular Linux user for you and send you SSH credentials, whatever would be easier.

**Comment by jcameron** [comment] 2022-06-01 05:05
Sure, the support module works! Just let me know on this bug when it's enabled ..

**Comment by neosonic2** [comment] 2022-06-01 12:52
@jcameron OK, I’ve now enabled remote support on our system and entered some notes when enabling that provide some additional details. I will be connected to the system throughout the day at various points via SSH and if you need any more info or etc. from me let me know.

**Comment by jcameron** [comment] 2022-06-02 04:21
Thanks, I am logging in now ... I will create a test domain to see if I can trigger this issue.

**Comment by neosonic2** [comment] 2022-06-02 04:27
@jcameron In the comments I left when enabling remote support, I actually provided one of our existing domains that needs to be deleted anyways and should reproduce this issue when deleted so you are welcome to delete that if you want rather than creating a new test domain.

**Comment by jcameron** [comment] 2022-06-02 04:49
I had a look, and I noticed one possible cause - when deleting a virtual server, I see the error message "no virtual host named jamietest.com exists"

Also, it seems like something is moving the Nginx config file for a domain from `/etc/nginx/vhosts/clients` to file with the `.original` suffix in `/etc/nginx/vhosts` . Do you have a pre-change custom script setup to do that?

**Comment by neosonic2** [comment] 2022-06-02 04:57
@jcameron Thanks for taking a look into this on the server for me.

One of the actions of the post-processing scripts Virtualmin runs after making changes to a virtual server (in this case, creating a new one) does indeed move the original Nginx virtual host file one level up from where Nginx expects to find it, while adding the .original suffix to the end. However, in its place is an updated virtual host file with additional directives for FastCGI caching and inclusion of a few files in /etc/nginx/conf.d based on the chosen server template. These are features the Nginx module does not currently support so I had to add them in manually. The original file is kept around with the .original suffix purely for backup/emergency purposes. When a virtual server is deleted, Virtualmin should still automatically remove the modified virtual host file since it has the same name as the one Virtualmin originally created.

**Comment by jcameron** [comment] 2022-06-02 05:28
Does that same script get run before a domain is deleted though? I think it is making the Nginx config for the domain invisible to Virtualmin..

**Comment by neosonic2** [comment] 2022-06-02 05:34
It does, yes, and I originally thought it didn’t delete any files related to virtual hosts, but looking at the code again (it’s been a long time since I’ve touched that part of the script), it actually does delete the virtual host file where Nginx expects it to be. So yes, I guess that would explain the error you are seeing then. I think I was originally trying to implement automatic deletion of the .original file  but for some reason added code to delete the actual virtual host instead; I can change this and run a new test to see if it resolves the issue.

**Comment by neosonic2** [comment] 2022-06-02 15:28
After modifying our post-run scripts to delete the .original file we created rather than the actual Nginx virtual host file, I can safely report this issue no longer occurs and SSL-related lines for the domain are properly removed from /etc/dovecot/dovecot.conf as they should be.

However, some weird text popped up while deleting the virtual server on the command line:

    Removing SSL from Nginx virtual host ..
id=webmin d=
id=usermin d=
id=dovecot d=HASH(0x556ba31638f8)
id=dovecot d=
id=postfix d=HASH(0x556ba31638f8)
    .. done

**Comment by jcameron** [comment] 2022-06-03 02:32
Oh sorry, that's some debug code that I added in order to attempt to resolve the issue! If my login access is still available, I can remove it ..

**Comment by jcameron** [comment] 2022-06-03 02:48
Ok, I've removed it. 

I guess we can close this issue now?

**Comment by neosonic2** [comment] 2022-06-04 17:13
@jcameron Yes and thank you for pointing out where I needed to change things on my end so the issue could be resolved.

**Comment by neosonic2** [comment] 2022-06-04 17:14
@jcameron I do also want to echo what others have said about moving SSL certificate entries from dovecot.conf to a local.conf file or something along those lines, but as you already mentioned that's a discussion for a different Github issue.

**Comment by jcameron** [comment] 2022-06-04 17:53
Yeah, that's a possibility if there is a local .conf file that's included in the main config file.

I'll look into adding support for this..

**Closed by jcameron** 2022-06-04 17:53 UTC

**Comment by neosonic2** [comment] 2022-10-11 09:05
@jcameron I can use the Virtualmin Support module to give you access to our production system running Virtualmin that is experiencing this issue, or just set up a regular Linux user for you and send you SSH credentials, whatever would be easier.
