### ISSUE TITLE
Scheduled Backups: Backup destination seem broken

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-gpl#542] opened 2023-03-31 07:01 UTC
Default `Backup destination` is `Local file or Directory` (when creating a new scheduled backup) but the is no input to select the destination. You need to select an oter iption an reselect `Local file or Directory` for the input to show

Probably broken due to #480

**Comment by PitWenkin** [comment] 2023-03-31 07:09
When cloning an existing schedule (with `Local file or directory`) selected as backup destination ,every setting is identical except for the backup destinations.

The dropdown is filled out properly but the is no input and thus not destination. Changing the dropdown  again allows to show the input, but it is empty.

Just saving (creating) the cloned backup without changing anything fails with "Failed to save scheduled backup : No backup destinations entered!"

**Comment by iliajie** [comment] 2023-03-31 09:46
Pit, hello!

Are you sure that you really have latest Virtualmin 7.5 installed? It works for me just fine.

**Comment by iliajie** [comment] 2023-03-31 17:50
Can you force reload the browser's page, and Webmin and try again? If that still doesn't work, could you provide step-by-step instructions on how this bug can be reproduced?

**Comment by PitWenkin** [comment] 2023-04-03 08:01
Still happening after server reboot.

Select `Scheduled Backups` from side-navigation `Backup and Restore`
Select `Add a new backup schedule`
Click on `Destination and format`
![1](https://user-images.githubusercontent.com/45786226/229447230-72c0e6e4-9d8d-4cd9-973c-9d3805183c02.png)
There is no input with id `dest0_file_i_2` (whole div with id `sel_dest0_mode_0` is hidden)

Click on `Backup destinations` and select anything except `Local file and directory`
![2](https://user-images.githubusercontent.com/45786226/229447450-5cb7e71b-e1f8-4505-b50e-7d23c0fe5a45.png)
Click on `Backup destinations` and select `Local file and directory`
![3](https://user-images.githubusercontent.com/45786226/229447536-adf406d7-1ada-414f-a5e1-de17a672b115.png)
Now there is an input with id `dest0_file_i_2`

**Comment by Stephano2000** [comment] 2023-04-03 08:34
I am able to reproduce the issue:
- Backup and Restore ->  Scheduled Backups
- Click "Add a new backup schedule"
- Click on "Destination and format"
- The Backup destinations dropdown is set by default to "Local file or directory", but the filename edit box is not visible
- Change the Backup destinations dropdown to "FTP server"
- Change the Backup destinations dropdown back to "Local file or directory"
- The filename edit box is now visible

**Comment by iliajie** [comment] 2023-04-03 15:11
Hello,

Thanks for the heads up. I understand what you're talking about but I am very confused with this issue. Because I remember clearly we had this issue in the past but later fixed it. Also, it works for me in macOS using Chrome and Firefox. It even works using Safari. Have a look please:

[Screen Recording 2023-04-03 at 17.53.29.webm](https://user-images.githubusercontent.com/4426533/229550618-7d261626-f4fd-4c00-bb05-485dd35d2b02.webm)

---

If you're sure it's not the browser issue, please share your `/etc/webmin/virtual-server/config` file for running deeper investigation on the problem.

**Comment by PitWenkin** [comment] 2023-04-05 00:40
Could it be a difference between 7.5 and 7.5 **Pro** (being released earlier or something like that)

**Comment by jcameron** [comment] 2023-04-05 01:09
The GPL and Pro versions should be identical in this aspect..

**Comment by PitWenkin** [comment] 2023-04-05 11:08
[/etc/webmin/virtual-server/config from my developer machine](https://github.com/virtualmin/virtualmin-gpl/files/11158023/config.txt) (IP's and such stuff has been redacted)

I originally found this bug on a server where I'm not using the default root user. But on my developer machine I'm using root and it happens anyway. Reproduced on Safari/Chrome on Mac and Edge on Windows

**Comment by iliajie** [comment] 2023-04-05 11:35
> The GPL and Pro versions should be identical in this aspect.

I see the source of the confusion and the problem. @PitWenkin We're sorry. You're right. This issue only shows itself in GPL version of the package, while Pro package has no such issue.

**Comment by chris001** [comment] 2023-04-05 17:29
Blue skies deep thought:  Would it not be great time saver to add CI test runs with the shiny new GitHub Actions (free and unlimited, whereas Travis CI is limited to ~ 10,000 free minutes per year!), it runs a test script on every commit to the main branch (or commit to any branch), as long as a test is written one time, it should always detect this issue - fail to create a local file backup on GPL version - so any regression of this bug could be fixed before a version release.

**Comment by iliajie** [comment] 2023-04-05 17:41
We simply do not have time to invest into Travis. Besides, we have tons of [functional testing](https://github.com/virtualmin/virtualmin-gpl/blob/master/functional-test.pl) happening at build time already.

**Comment by chris001** [comment] 2023-04-05 21:18
I could setup actions to run that functional test script on every commit to master.

**Comment by jcameron** [comment] 2023-04-06 02:25
We do run the tests before every release though..

**Comment by chris001** [comment] 2023-04-06 05:44
Both ways could and probably should be done.  At least tried out, it's free, and automatic, no added human intervention needed.  Github made this feature, and all the serious apps use Actions, for peace of mind and effortless continuous tests of master.

**Comment by PitWenkin** [comment] 2023-04-13 11:07
Apart from the discussion about functional tests, will this be fixed?

**Comment by iliajie** [comment] 2023-04-13 11:13
> Apart from the discussion about functional tests, will this be fixed?

Yes, it will be fixed in the next Virtualmin release!

**Closed** 2023-04-13 12:18 UTC
