### ISSUE TITLE
`Configure Website` goes to `Configure SSL Website` when I change virtual server

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#713] opened 2023-12-09 17:02 UTC
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.8.2       |
|  Theme version       |     21.09.5      |
|  Package updates     |      19  package updates are available   |

## The background
I have been going through my virtual servers removing `index.php4` and `index.php5` from my server directives and becasue I have the option selected to load the same page when swapping virtual server this should of been easy.

## The issue
- I edit a virtual server directives `Virtualmin --> Services --> Configure Website --> Edit Directives` and removed the offending items
- i clicked `save`
- i then swapped the virtual server to the next one but the page `Configure SSL Website` is opened and not the `Configure Website` page.

NB: it is also the same if I do `save and close` and then change virtual server

**Comment by jcameron** [comment] 2023-12-09 22:14
@iliajie the authentic theme does this page update when changing domains, right?

**Comment by iliajie** [comment] 2023-12-10 13:31
Yes, it seems like a bug on the theme side! Thanks for the heads up. I will update this ticket with progress ..

**Comment by iliajie** [comment] 2023-12-10 17:49
I have found the cause for this bug. It will be fixed in the next Webmin and Authentic Theme release.

**Closed by iliajie** 2023-12-10 17:49 UTC
