### ISSUE TITLE
TTL of DNS-Records not properly applied for sub-servers 

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-gpl#741] opened 2024-01-18 17:12 UTC
When manually editing the DNS Records of a virtual server with sub-server(s), all changes are (at least as far as I checked) correctly copied/applied to the DNS Records of the sub-server(s), apart from `$ttl`-line and the SOA entry.

As far as I understand, or could reproduce the new `$ttl`- line is added above the old one instead of replacing it.

Having the following situation
```
$ttl 3600
@	IN	SOA	ns.example.com. root.ns.example.com. (
			1234567801
			10800
			3600
			604800
			38400 )
@	IN	NS	ns.example.com.
toplevelserver.com	IN	A	127.0.0.1
```
and
```
$ttl 3600
@	IN	SOA	ns.example.com. root.ns.example.com. (
			2345678901
			10800
			3600
			604800
			38400 )
@	IN	NS	ns.example.com.
subserver.com	IN	A	127.0.0.1
```

would change to this after manually changing the `$ttl`-value and incrementing the SOA serial on the top-level server:
```
$ttl 600
@	IN	SOA	ns.example.com. root.ns.example.com. (
			1234567802
			10800
			3600
			604800
			38400 )
@	IN	NS	ns.example.com.
toplevelserver.com	IN	A	127.0.0.1
```
and
```
$ttl 600
$ttl 3600
@	IN	SOA	ns.example.com. root.ns.example.com. (
			2345678902
			10800
			3600
			604800
			38400 )
@	IN	NS	ns.example.com.
subserver.com	IN	A	127.0.0.1
```

Only the last `$ttl`-value seems to be applied, and therefore not changing the TTL at all. After multiple changes to the `$ttl`-value there might be multiple lines. I found one with:

```
$ttl 600
$ttl 3600
$ttl 38400
…
```

I don't know if they are ordered in increasing duration, or simply the newest on top …

I understand that automatically/blindly overwriting the SOA-serial on the sub-server with the new one of the top-level server could have negative effects, if the serial of the sub-server was greater than the new serial of the top-level server … but having them on the same value would fro a human stand-point probably not be wrong …

**Comment by jcameron** [comment] 2024-01-18 22:50
If Virtualmin is adding multiple `$ttl` lines, that's clearly a bug! Where in the UI are you changing the TTL?

**Comment by PitWenkin** [comment] 2024-01-19 07:52
Changes on the top-level server have been done in Virtualmin under `DNS Settings` > `DNS Records`
![Screenshot 2024-01-19 at 08 41 34](https://github.com/virtualmin/virtualmin-gpl/assets/45786226/15f86bad-e842-4b2a-8b3c-c0714ceb6301)


Fixes on the sub-server have been done in Webmin under `Servers` > `BIND DNS Server`
![Screenshot 2024-01-19 at 08 46 31](https://github.com/virtualmin/virtualmin-gpl/assets/45786226/cf377f41-7bb2-45a2-a29f-cd4de6936e53)

Even though there is a warning that changes will be overwritten, the `$ttl` fix seem to be kept.
(I have not yet changed the value on the top-level server after my fix worked …)

**Comment by jcameron** [comment] 2024-01-20 05:21
Hmm, that does look like a bug. Looking into it now ....

**Comment by jcameron** [comment] 2024-01-20 05:34
Ah ok I found the cause of this - thanks for reporting it! It will be fixed in the next Virtualmin release..

**Closed by jcameron** 2024-01-20 05:34 UTC
