### ISSUE TITLE
Limits: Missing menu links

### ISSUE THREAD

**Issue by iliajie** [virtualmin/virtualmin-gpl#503] opened 2023-01-10 23:28 UTC
If you change the limits (i.e. at Administration Options ⇾ Edit Owner Limits) and allow virtual server owners to delete virtual servers there is no menu link appearing in server owner mode. Pro users can delete it from List Virtual Servers page. But I suppose GPL users won't be able to do it .. so I assume we want to add Disable and Delete section to navigation menu if either Can delete virtual servers or Can disable virtual servers is enabled in limits?

**Comment by jcameron** [comment] 2023-01-11 07:35
OK I found the cause of this - the left menu cache isn't fully updated when changing limits. I've checked in a fix for this..

**Closed by jcameron** 2023-01-11 07:35 UTC

**Comment by iliajie** [comment] 2023-01-11 11:06
Thanks, Jamie. However, I checked the cache issue at the first place (purging all cache manually) but that wasn't the solution to the problem. Also, this patch doesn't solve it.

I think, we need to look if we run checks correctly before printing the sub-menu..

**Comment by iliajie** [comment] 2023-01-11 13:38
i.e. `if (&can_disable_domain($d)) {}` and `if (&can_delete_domain($d)) {}` inside of `get_domain_actions` never allow to add those links, even though it's enabled on limits page, and can be successfully deleted using List Virtual Servers page.

**Comment by jcameron** [comment] 2023-01-12 00:48
Make sure that the domain owner isn't selecting their own top-level domain - this can never be deleted or disabled.

**Comment by iliajie** [comment] 2023-01-12 00:52
Oh, I see now. I was exactly trying to do that, i.e. to disable/delete own top-level domain. It makes sense now. Thanks for clearing this up! No issue here then.
